import type { TempatIbadah } from "../types";

import masjidImg from "@/assets/religious-place/masjid.webp";
import gerejaImg from "@/assets/religious-place/gereja.webp";
import viharaImg from "@/assets/religious-place/vihara.webp";
import klentengImg from "@/assets/religious-place/klenteng-vihara.webp";

import masjidIcon from "@/assets/religious-icons/masjid.svg";
import gerejaIcon from "@/assets/religious-icons/gereja.svg";
import viharaIcon from "@/assets/religious-icons/vihara.svg";
import klentengIcon from "@/assets/religious-icons/klenteng-vihara.svg";

export const categories = ["Semua", "Masjid", "Gereja", "Klenteng", "Vihara"];

export const tempatIbadahData: TempatIbadah[] = [
  {
    id: 1,
    name: "Masjid Agung Syekh Quro Karawang",
    type: "Masjid",
    kelurahan: "Karawang Kulon",
    address: "Jl. Alun-Alun Barat No.1, Karawang Kulon, Kec. Karawang Barat",
    nazhir: "H. Asep Saepudin, M.A.",
    status: "Tersertifikasi Wakaf",
    capacity: "3.000 Jamaah",
    image: masjidImg,
    icon: masjidIcon,
  },
  {
    id: 2,
    name: "Gereja Christ the King",
    type: "Gereja",
    kelurahan: "Adiarsa Barat",
    address: "Jl. Parahiyangan No.45, Adiarsa Barat, Kec. Karawang Barat",
    nazhir: "Romo Yohanes",
    status: "Tersertifikasi",
    capacity: "2.500 Jemaat",
    image: gerejaImg,
    icon: gerejaIcon,
  },
  {
    id: 3,
    name: "Masjid Jami An-Nur Tanjungpura",
    type: "Masjid",
    kelurahan: "Tanjungpura",
    address: "Jl. Proklamasi Gg. Masjid No.18, Tanjungpura, Kec. Karawang Barat",
    nazhir: "K.H. Ahmad Dahlan",
    status: "Tersertifikasi Wakaf",
    capacity: "800 Jamaah",
    image: masjidImg,
    icon: masjidIcon,
  },
  {
    id: 4,
    name: "Vihara Dharma Ayu",
    type: "Vihara",
    kelurahan: "Tunggakjati",
    address: "Jl. Syeh Quro, Tunggakjati, Kec. Karawang Barat",
    nazhir: "Biksu Dhammacaro",
    status: "Proses Sertifikasi",
    capacity: "500 Umat",
    image: viharaImg,
    icon: viharaIcon,
  },
  {
    id: 5,
    name: "Masjid Baiturrahman Adiarsa",
    type: "Masjid",
    kelurahan: "Adiarsa Barat",
    address: "Perumahan Adiarsa Indah Blok C, Adiarsa Barat, Kec. Karawang Barat",
    nazhir: "H. Bambang Irawan",
    status: "Tersertifikasi Wakaf",
    capacity: "600 Jamaah",
    image: masjidImg,
    icon: masjidIcon,
  },
  {
    id: 6,
    name: "Klenteng Bio Kwan Tee Koen",
    type: "Klenteng",
    kelurahan: "Nagasari",
    address: "Jl. Tuparev No.10, Nagasari, Kec. Karawang Barat",
    nazhir: "Pengurus Yayasan",
    status: "Tersertifikasi",
    capacity: "700 Umat",
    image: klentengImg,
    icon: klentengIcon,
  },
  {
    id: 7,
    name: "Gereja HKBP Karawang",
    type: "Gereja",
    kelurahan: "Nagasari",
    address: "Jl. R.S. Suria Kertawiguna No.8, Nagasari, Kec. Karawang Barat",
    nazhir: "Pdt. R. Siregar",
    status: "Tersertifikasi",
    capacity: "1.200 Jemaat",
    image: gerejaImg,
    icon: gerejaIcon,
  },
  {
    id: 8,
    name: "Masjid Al-Jihad Karawang",
    type: "Masjid",
    kelurahan: "Karawang Wetan",
    address: "Jl. A. Yani No.22, Karawang Wetan, Kec. Karawang Barat",
    nazhir: "H. Ujang Supriyatna",
    status: "Tersertifikasi Wakaf",
    capacity: "1.500 Jamaah",
    image: masjidImg,
    icon: masjidIcon,
  },
  {
    id: 9,
    name: "Vihara Avalokitesvara",
    type: "Vihara",
    kelurahan: "Tanjungmekar",
    address: "Jl. Pangkal Perjuangan, Tanjungmekar, Kec. Karawang Barat",
    nazhir: "Biksu Nyanabhadra",
    status: "Tersertifikasi",
    capacity: "450 Umat",
    image: viharaImg,
    icon: viharaIcon,
  },
  {
    id: 10,
    name: "Gereja Bethel Indonesia (GBI) Karawang",
    type: "Gereja",
    kelurahan: "Karawang Kulon",
    address: "Jl. Kertabumi No.34, Karawang Kulon, Kec. Karawang Barat",
    nazhir: "Pdt. Samuel",
    status: "Proses Sertifikasi",
    capacity: "800 Jemaat",
    image: gerejaImg,
    icon: gerejaIcon,
  },
  {
    id: 11,
    name: "Masjid Al-Barkah",
    type: "Masjid",
    kelurahan: "Tanjungpura",
    address: "Jl. Proklamasi No.45, Tanjungpura, Kec. Karawang Barat",
    nazhir: "H. Abdullah",
    status: "Tersertifikasi Wakaf",
    capacity: "400 Jamaah",
    image: masjidImg,
    icon: masjidIcon,
  },
  {
    id: 12,
    name: "Gereja Katolik Santa Maria",
    type: "Gereja",
    kelurahan: "Karawang Kulon",
    address: "Jl. Tuparev No.112, Karawang Kulon, Kec. Karawang Barat",
    nazhir: "Romo Antonius",
    status: "Tersertifikasi",
    capacity: "1.000 Jemaat",
    image: gerejaImg,
    icon: gerejaIcon,
  },
  {
    id: 13,
    name: "Vihara Buddha Dharma",
    type: "Vihara",
    kelurahan: "Adiarsa Barat",
    address: "Jl. KH. Dewantara No.2, Adiarsa Barat, Kec. Karawang Barat",
    nazhir: "Biksu Silananda",
    status: "Proses Sertifikasi",
    capacity: "350 Umat",
    image: viharaImg,
    icon: viharaIcon,
  },
];
